# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5vZ2xdmyZss0245lWiqcTPceFgRAudA
"""

import streamlit as st
import pandas as pd
import xgboost as xgb
import joblib
import numpy as np

# --- 1. SETTING & CONFIG ---
st.set_page_config(
    page_title="TB Treatment Prediction",
    page_icon="🏥",
    layout="wide"
)

# --- 2. LOAD MODEL & ASSETS ---
@st.cache_resource
def load_assets():
    try:
        model = joblib.load('xgb_tb_model.pkl')
        features = joblib.load('model_features.pkl')
        return model, features
    except FileNotFoundError:
        st.error("❌ ไม่พบไฟล์โมเดล! กรุณาตรวจสอบว่ามีไฟล์ 'xgb_tb_model.pkl' และ 'model_features.pkl' อยู่ในโฟลเดอร์เดียวกัน")
        return None, None

model, model_features = load_assets()

# --- 3. ENCODING FUNCTION ---
def encode_inputs(input_dict):
    """
    ฟังก์ชันแปลงค่า Text จากหน้าเว็บให้เป็นตัวเลขตาม Dataset
    (โปรดปรับตัวเลข Mapping ให้ตรงกับไฟล์ Excel ของคุณ)
    """
    mappings = {
        'Gender': {'ชาย': 0, 'หญิง': 1},
        'HIV': {'ไม่ติดเชื้อ (Negative)': 0, 'ติดเชื้อ (Positive)': 1, 'ไม่ทราบ/ไม่ตรวจ': 2},
        'Take a Co-Trimoxazole': {'No': 0, 'Yes': 1},
        'Treatment of ARV': {'No': 0, 'Yes': 1},
        ' AFB resulf of first month': {'Negative': 0, '1+': 1, '2+': 2, '3+': 3, 'Scanty': 4},
        'position of TB': {'ในปอด': 0, 'นอกปอด': 1}
    }

    encoded = input_dict.copy()
    for col, mapping in mappings.items():
        if col in encoded:
            encoded[col] = mapping.get(encoded[col], 0)
    return encoded

# --- 4. USER INTERFACE (UI) ---
st.title("🏥 ระบบพยากรณ์ความเสี่ยงผลการรักษาวัณโรค (TB)")
st.markdown("กรุณากรอกข้อมูลผู้ป่วยด้านล่าง เพื่อให้ AI ช่วยประเมินความเสี่ยงในการรักษา")

if model:
    with st.form("prediction_form"):
        col1, col2, col3 = st.columns(3)

        with col1:
            st.subheader("📌 ข้อมูลพื้นฐาน")
            age = st.number_input("อายุ (Age)", min_value=0, max_value=120, value=45)
            gender = st.selectbox("เพศ (Gender)", ["ชาย", "หญิง"])
            bmi = st.number_input("ดัชนีมวลกาย (BMI)", min_value=10.0, max_value=50.0, value=20.0, step=0.1)
            duration = st.number_input("ระยะเวลาการรักษา (Duration - วัน)", min_value=0, value=180)

        with col2:
            st.subheader("🩺 ประวัติสุขภาพ")
            hiv = st.selectbox("สถานะ HIV", ["ไม่ติดเชื้อ (Negative)", "ติดเชื้อ (Positive)", "ไม่ทราบ/ไม่ตรวจ"])
            dm = st.selectbox("เบาหวาน (Diabetes Mellitus)", [0, 1], help="0=No, 1=Yes")
            ckd = st.selectbox("โรคไตเรื้อรัง (CKD)", [0, 1])
            copd = st.selectbox("โรคปอดอุดกั้นเรื้อรัง (COPD)", [0, 1])
            liver = st.selectbox("โรคตับ (Liver Disease)", [0, 1])

        with col3:
            st.subheader("🧪 ผลการตรวจ")
            afb = st.selectbox("ผล AFB เดือนแรก", ["Negative", "1+", "2+", "3+", "Scanty"])
            pos_tb = st.selectbox("ตำแหน่งของโรค (Position)", ["ในปอด", "นอกปอด"])
            follow_up = st.number_input("จำนวนครั้งที่ Follow up", min_value=0, value=1)
            arv = st.selectbox("ได้รับยา ARV หรือไม่", ["No", "Yes"])

        # ปุ่มกดทำนาย
        submit_btn = st.form_submit_button("วิเคราะห์ผลการรักษา")

    # --- 5. PREDICTION LOGIC ---
    if submit_btn:
        # เก็บข้อมูลดิบลง Dict
        raw_inputs = {
            'Age': age,
            'Gender': gender,
            'BMI': bmi,
            'Duration': duration,
            'HIV': hiv,
            'Diabetes Mellitus': dm,
            'Chronic Kidney Disease': ckd,
            ' Chronic Obstructive Pulmonary Disease': copd,
            'Liver Disease': liver,
            ' AFB resulf of first month': afb,
            'position of TB': pos_tb,
            '(TB F/U) follow up': follow_up,
            'Treatment of ARV': arv
        }

        # แปลงเป็นตัวเลข
        encoded_data = encode_inputs(raw_inputs)

        # สร้าง DataFrame โดยอิงจากลำดับคอลัมน์ที่ใช้เทรน (Features)
        input_df = pd.DataFrame(0, index=[0], columns=model_features)
        for col in encoded_data:
            if col in input_df.columns:
                input_df[col] = encoded_data[col]

        # ทำนายผล
        prediction = model.predict(input_df)[0]
        probability = model.predict_proba(input_df)[0][1]

        # แสดงผลลัพธ์
        st.subheader("📊 ผลการวิเคราะห์")

        if prediction == 1:
            st.error(f"⚠️ **กลุ่มเสี่ยง:** มีโอกาสเกิดผลการรักษาที่ไม่พึงประสงค์ (เสียชีวิต/ล้มเหลว/ขาดยา)")
            st.progress(float(probability))
            st.write(f"ระดับความเสี่ยง: {probability:.2%}")
        else:
            st.success(f"✅ **กลุ่มปกติ:** มีแนวโน้มรักษาหายหรือครบตามกำหนด")
            st.progress(float(probability))
            st.write(f"โอกาสความน่าจะเป็นที่จะเป็นกลุ่มเสี่ยง: {probability:.2%}")

        st.info("หมายเหตุ: ผลลัพธ์นี้เป็นเพียงการพยากรณ์เบื้องต้นจาก AI เท่านั้น โปรดปรึกษาแพทย์ผู้เชี่ยวชาญ")

else:
    st.warning("ระบบไม่พร้อมใช้งาน เนื่องจากโหลดโมเดลไม่สำเร็จ")